-- ============================================================
-- Catalogo nacional de PDV, migrado desde 'NOMBRES PDV.xlsx'
-- ============================================================

insert into public.pdvs (nombre) values ('AZUY CUENCA 9 DE OCTUBRE') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('AZUY CUENCA AMERICAS') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('AZUY CUENCA AV. SIMON BOLIVAR') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('AZUY CUENCA CALLE LARGA') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('AZUY CUENCA DON BOSCO') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('AZUY CUENCA REMIGIO CRESPO') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('AZUY CUENCA RICAURTE') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('AZUY CUENCA TOTORACOCHA') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('AZUY CUENCA UNCOVIA') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('AZUY GUALACEO') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('AZUY PAUTE') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('AZUY SIGSIG') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('BOLI GUARANDA PARQUE CENTRAL') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('CAÑR AZOGUES AV. 10 DE AGOSTO') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('CAÑR AZOGUES PARQUE DEL MIGRANTE') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('CAÑR BIBLIAN') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('CAÑR CAÑAR') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('CHIM CAJABAMBA') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('CHIM CUMANDA') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('CHIM GUANO') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('CHIM RIOBAMBA CENTRO AV. 10 DE AGOSTO') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('CHIM RIOBAMBA LA VASIJA') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('CHIM RIOBAMBA MATRIZ') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('CHIM RIOBAMBA NORTE AV. LIZARZABURO') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('CHIM RIOBAMBA SUR AV. JUAN FELIX') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('CHIM RIOBAMBA TERMINAL') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('COTX LA MANA') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('COTX LATACUNGA AV. 2 DE MAYO') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('COTX SALCEDO') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('COTX SAQUISILI') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('ELORO EL GUABO') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('ELORO HUAQUILLAS') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('ELORO MACHALA AV. LAS PALMERAS') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('ELORO MACHALA AV. ROCAFUERTE') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('ELORO MACHALA HECTOR TORO') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('Eloro Machala Terminal') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('ELORO PASAJE') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('ELORO PIÑAS') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('ELORO SANTA ROSA') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('ESME ATACAMES') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('ESME LAS PALMAS') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('ESME QUININDE') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('GUAY DURAN SHOPPING') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('GUAY GYE 17 Y PORTETE') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('GUAY GYE CENTENARIO') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('GUAY GYE CENTRO AV. DEL EJERCITO') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('GUAY GYE CHONGON') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('GUAY GYE COOP JUAN MONTALVO') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('GUAY GYE CRISTO DEL CONSUELO') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('GUAY GYE FLORESTA 3') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('GUAY GYE GARZO CENTRO') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('GUAY GYE GUASMO CENTRO') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('GUAY GYE GUASMO MATERNIDAD') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('GUAY GYE LA ALBORADA 12') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('GUAY GYE LAS PEÑAS') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('GUAY GYE LOS ESTEROS') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('GUAY GYE MAPASINGUE') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('GUAY GYE MUCHO LOTE 1') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('GUAY GYE PLAZA SAN FRANCISCO') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('GUAY GYE RIOCENTRO SUR') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('GUAY GYE SAMANES 4') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('GUAY GYE SAUCES 6') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('GUAY GYE TIA PORTETE') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('GUAY GYE URDANETA') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('GUAY GYE URDESA') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('GUAY JUJAN') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('GUAY MILAGRO AV. JUAN MONTALVO') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('GUAY MILAGRO LOS CHIRIJOS') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('GUAY MILAGRO SUR AV. CRISTOBAL COLON') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('GUAY NARANJAL') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('GUAY PLAZA TIA DURAN') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('GUAY SALITRE') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('GUAY SAMBORONDON') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('GUAY SANTA LUCIA') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('GUAY VILLAMIL PLAYAS') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('GUAY VILLAMIL PLAYAS SHOPPING') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('IMBA IBARRA MARIANO ACOSTA') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('IMBA OTAVALO') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('LOJA AV. 18 DE NOVIEMBRE') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('LOJA AV. 8 DE DICIEMBRE') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('LOJA CATAMAYO') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('LOJA PARQUE BOLIVAR') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('LRIO BABAHOYO AV 5. DE JUNIO') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('LRIO BABAHOYO SHOPPING') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('LRIO BUENA FE') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('LRIO MONTALVO') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('LRIO QUEVEDO AV. 7 DE OCTUBRE') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('LRIO QUEVEDO SAN CAMILO') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('LRIO QUINSALOMA') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('LRIO VENTANAS') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('LRIO VINCES') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('MANB MANTA CALLE 13') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('MANB PORTOVIEJO AV. MANABI') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('MORO MACAS') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('MORO SUCUA') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('NAPO TENA AV 15 DE NOVIEMBRE') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('NAPO TENA HOSPITAL JOSE VELASCO') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('NAPO TENA PARQUE LINEAL') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('OREL EL COCA CALLE NAPO') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('OREL EL COCA TERMINAL') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('OREL JOYA DE LOS SACHAS') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('OREL LORETO') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('PAST PUYO CENTRO') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('PAST PUYO EL OBRERO') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('PAST PUYO PRINCIPAL') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('PICH CAYAMBE CENTRO') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('PICH LOS BANCOS') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('PICH MEJIA MACHACHI') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('PICH PUERTO QUITO') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('PICH QUITO CENTRO HISTORICO') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('PICH QUITO CENTRO SAN FRANCISCO') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('PICH QUITO EL QUINCHE') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('PICH QUITO GUAYLLABAMBA') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('PICH QUITO LA KENNEDY') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('PICH QUITO NORTE CARAPUNGO') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('PICH QUITO NORTE COTOCOLLAO') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('PICH QUITO NORTE EL CONDADO') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('PICH QUITO NORTE LA CAROLINA') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('PICH QUITO NORTE LA COLON') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('PICH QUITO NORTE NAYON') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('PICH QUITO NORTE PIFO') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('PICH QUITO NORTE U CENTRAL') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('PICH QUITO REAL AUDIENCIA') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('PICH QUITO SUR AMAGUAÑA') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('PICH QUITO SUR CAUPICHO') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('PICH QUITO SUR CDLA IBARRA') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('PICH QUITO SUR CHILLOGALLO') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('PICH QUITO SUR CONOCOTO') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('PICH QUITO SUR LA MICHELENA') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('PICH QUITO SUR NUEVA AURORA') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('PICH QUITO SUR SOLANDA AJAVI') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('PICH QUITO SUR VILLAFLORA') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('PICH RUMIÑAHUI SAN RAFAEL') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('PICH SANGOLQUI') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('STAEL LA LIBERTAD') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('STAEL SALINAS') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('STAEL SANTA ELENA') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('SUCU LAGO AGRIO AV. VENEZUELA') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('SUCU LAGO AGRIO PARQUE RECREACIONAL') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('SUCU SHUSHUFINDI') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('TSAC LA CONCORDIA') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('TSAC SANTO DOMINGO AV LORENA') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('TSAC SANTO DOMINGO CALLE 29 DE MAYO') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('TSAC SANTO DOMINGO LA CHORRERA') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('TSAC SANTO DOMINGO SHOPPING') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('TUNG AMBATO CENTRO') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('TUNG AMBATO FICOA') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('TUNG AMBATO IZAMBA') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('TUNG AMBATO MALL DE LOS ANDES') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('TUNG AMBATO MAYORISTA') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('TUNG AMBATO STA ROSA') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('TUNG AMBATO TERESA FLOR') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('TUNG PELILEO') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('TUNG PILLARO') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('ZAMR YANTZAZA') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('ZAMR ZAMORA') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('TUNG AMBATO PASEO SHOPPING') on conflict (nombre) do nothing;
insert into public.pdvs (nombre) values ('GUAY PEDRO CARBO') on conflict (nombre) do nothing;
