-- ============================================================
-- Sincronizacion incremental de SEGUIMIENTO desde el Excel
-- Solo inserta filas cuya firma (escuela+fecha+cargo+aspirantes)
-- no exista ya en la base, para no duplicar ni tocar lo existente.
-- ============================================================

insert into public.seguimientos (escuela_id, escuela_nombre_libre, fecha_capacitacion, num_aspirantes, aspirantes, cargo, num_ingreso, aspirante_aprobado, pdv_solicitud, encuesta, fecha_ingreso, reembolso, observaciones, analista, pago1, pago2) values (null, null, '2026-06-04', 1, '[{"nombre":"EMILY AMAYA","aprobado":false}]'::jsonb, 'POLI', null, null, 'RIOBAMBA 10 DE AGOSTO', null, null, null, null, null, null, null);
insert into public.seguimientos (escuela_id, escuela_nombre_libre, fecha_capacitacion, num_aspirantes, aspirantes, cargo, num_ingreso, aspirante_aprobado, pdv_solicitud, encuesta, fecha_ingreso, reembolso, observaciones, analista, pago1, pago2) values ((select id from public.escuelas where nombre = 'TUNG AMBATO CENTRO'), null, '2026-08-31', 3, '[{"nombre":"Paola Elizabeth Salán Barona","aprobado":false},{"nombre":"Gabriela Morales","aprobado":false},{"nombre":"Geomara Lisbeth Salinas Flores","aprobado":false}]'::jsonb, 'POLI', null, 'Paola Elizabeth Salán Barona', 'AMBATO - TERESA FLOR', null, '2026-09-05', null, null, null, null, null);
insert into public.seguimientos (escuela_id, escuela_nombre_libre, fecha_capacitacion, num_aspirantes, aspirantes, cargo, num_ingreso, aspirante_aprobado, pdv_solicitud, encuesta, fecha_ingreso, reembolso, observaciones, analista, pago1, pago2) values ((select id from public.escuelas where nombre = 'TUNG AMBATO TERESA FLOR'), null, '2026-09-06', 1, '[{"nombre":"Karla Collaguazo","aprobado":false}]'::jsonb, 'ADM', null, 'Karla Collaguazo', 'PICHINCHA - MACHACHI', null, '2026-09-07', null, null, null, null, null);
insert into public.seguimientos (escuela_id, escuela_nombre_libre, fecha_capacitacion, num_aspirantes, aspirantes, cargo, num_ingreso, aspirante_aprobado, pdv_solicitud, encuesta, fecha_ingreso, reembolso, observaciones, analista, pago1, pago2) values ((select id from public.escuelas where nombre = 'MILAGRO CENTRO  Av JUAN MONTALVO'), null, '2026-08-04', 3, '[{"nombre":"Kevin Daniel Sanchez","aprobado":false},{"nombre":"Katherine Lisbeth Gavilanes","aprobado":false},{"nombre":"Marilyn Lizbeth Villareal","aprobado":false}]'::jsonb, 'ADM', null, 'Katherine Lisbeth', 'GUAYAQUIL - MILAGRO SUR', null, '2026-09-07', null, 'El personal se quedo 1 dia en el pdv milagro sur donde presento problemas con el pdv (Microhondas Dañado , Sin inventario , etc', null, null, null);
insert into public.seguimientos (escuela_id, escuela_nombre_libre, fecha_capacitacion, num_aspirantes, aspirantes, cargo, num_ingreso, aspirante_aprobado, pdv_solicitud, encuesta, fecha_ingreso, reembolso, observaciones, analista, pago1, pago2) values ((select id from public.escuelas where nombre = 'TUNG AMBATO TERESA FLOR'), null, '2026-09-09', 1, '[{"nombre":"Lisseth Romero","aprobado":false}]'::jsonb, 'ZONAL', null, 'Lisseth Romero', 'ZONA 4', null, '2026-09-07', null, null, null, null, null);
insert into public.seguimientos (escuela_id, escuela_nombre_libre, fecha_capacitacion, num_aspirantes, aspirantes, cargo, num_ingreso, aspirante_aprobado, pdv_solicitud, encuesta, fecha_ingreso, reembolso, observaciones, analista, pago1, pago2) values ((select id from public.escuelas where nombre = 'GUAY GYE GARZO CENTRO'), null, '2026-09-11', 1, '[{"nombre":"Ivania Figueroa","aprobado":false}]'::jsonb, 'POLI', null, null, 'BABAHOYO SHOPPING', null, null, null, 'Ultimo dia de capacitacion Pdv Garzocentro', null, null, null);
insert into public.seguimientos (escuela_id, escuela_nombre_libre, fecha_capacitacion, num_aspirantes, aspirantes, cargo, num_ingreso, aspirante_aprobado, pdv_solicitud, encuesta, fecha_ingreso, reembolso, observaciones, analista, pago1, pago2) values ((select id from public.escuelas where nombre = 'GUAY GYE GARZO CENTRO'), null, '2026-09-14', 1, '[{"nombre":"Carolina Cedeño","aprobado":false}]'::jsonb, 'POLI MT', null, null, 'GUAYAQUIL - RIOCENTRO SUR', null, null, null, null, null, null, null);
insert into public.seguimientos (escuela_id, escuela_nombre_libre, fecha_capacitacion, num_aspirantes, aspirantes, cargo, num_ingreso, aspirante_aprobado, pdv_solicitud, encuesta, fecha_ingreso, reembolso, observaciones, analista, pago1, pago2) values ((select id from public.escuelas where nombre = 'CHIM RIOBAMBA SUR JUAN FÉLIX'), null, '2026-09-15', 3, '[{"nombre":"Dave Vasquez","aprobado":false},{"nombre":"Angelica Moreira","aprobado":false},{"nombre":"Georgina Mora","aprobado":false}]'::jsonb, 'POLI MT', null, null, 'PDV RIOBAMBA TERMINAL', null, null, null, null, null, null, null);
